-- 平衡参数
TUNING.SPEAR_WATHGRITHR_LIGHTNING_LUNGE_COOLDOWN = 6
TUNING.SPEAR_WATHGRITHR_LIGHTNING_CHARGED_LUNGE_COOLDOWN = 3

TUNING.INSPIRATION_GAIN_RATE = 0
TUNING.BATTLESONG_DURABILITY_MOD = 0.66
TUNING.BATTLESONG_INSTANT_VALUE = 0.5
TUNING.BATTLESONG_PANIC_TIME = 6

TUNING.WATHGRITHR_SING_INSPIRE_PER_HIRE = 5
TUNING.WATHGRITHR_SING_INSPIRE_PER_CROP = 1
TUNING.WATHGRITHR_SING_INSPIRE_COOLDOWN = 60
TUNING.WATHGRITHR_SING_DAILY_HIRE_MAX = 20
TUNING.WATHGRITHR_SING_DAILY_CROP_MAX = 10
TUNING.WATHGRITHR_SING_MAX_FOLLOWERS = 4
TUNING.WATHGRITHR_SING_HIRE_TIME = TUNING.TOTAL_DAY_TIME / 4
