-- 平衡参数
TUNING.SPEAR_WATHGRITHR_LIGHTNING_LUNGE_COOLDOWN = 6
TUNING.SPEAR_WATHGRITHR_LIGHTNING_CHARGED_LUNGE_COOLDOWN = 3

TUNING.INSPIRATION_GAIN_RATE = 0
TUNING.BATTLESONG_DURABILITY_MOD = 0.66
TUNING.BATTLESONG_INSTANT_VALUE = 0.5
TUNING.BATTLESONG_PANIC_TIME = 6

-- 独唱
TUNING.WATHGRITHR_SING_RANGE = TUNING.ONEMANBAND_RANGE
TUNING.WATHGRITHR_SING_VERSE_INTERVAL = 2
TUNING.WATHGRITHR_SING_VERSE_COST = 5
TUNING.WATHGRITHR_SING_DURATION = 10
TUNING.WATHGRITHR_SING_COOLDOWN = 10
TUNING.WATHGRITHR_SING_HIRE_TIME = 30
TUNING.WATHGRITHR_SING_DOMESTICATION_PER_VERSE = 0.002
TUNING.WATHGRITHR_SING_DOMESTICATION_CAP_PER_DAY = 0.01
TUNING.WATHGRITHR_SING_MAX_FOLLOWERS = 6
